### PR TITLE
fix: image 404 not found

### PR DESCRIPTION
**Pull request by digglife**
Some of the images in the documentation can't display due to incorrect file name. 

#### Changelog

**Changed**

- fix incorrect image file names in markdown. 

#### Testing / Reviewing

a throwaway bash script for finding incorrect image filenames in markdown.

```bash
grep -E -i -r --include '*.md' '\.(png|svg)' . | awk -F':' '{print $2}' | gsed -E 's/.*\(\.?\/.*\/(.*\.(png|svg))\).*/\1/g' | sort | uniq | while read -r i;do
    find . -name "$i" | grep -q . || echo "$i" 
done
```

### CODE REVIEW

**Comment by tlawrie** [comment]
Hi @digglife would you also be able to run that against @morarucostel 3.5.0 branch?

**Comment by tlawrie** [comment]
And is there a related github issue to this PR

**Comment by digglife** [comment]
@tlawrie 

Yeah it also affects files in `3.5.0` folder of `release-3-5-0` branch. I opened an issue #50 for describing the problem. Please feel free to close this one.

**Comment by timrbula** [comment]
@digglife Thanks for the two PRs. I will close this one.

**Pull request closed without merging**
