### PR TITLE
Revert "Describing how to secure the Grafana UI using auth proxy"

### PR DESCRIPTION
**Pull request by morarucostel**
Reverts boomerang-io/useboomerang.io#40

### CODE REVIEW

**Comment by morarucostel** [comment]
@tlawrie Just reverting the changes I've done. 
Where would be a good place to place this information?

**Comment by tlawrie** [comment]
Good question. 

Options as far as I can think:
1. Merge it into this location anyway
2. Create a separate location for general docs (and add to the docs tile screen)
3. Turn into a blog post and link to it as additional information or as an external tile.

What are your thoughts?

**Comment by morarucostel** [comment]
I'm between options 2 and 3. 
Opening a new doc section about everything else and keeping it in the platform docs might be difficult to maintain in the long run. 
I tend towards option 3, I guess.

**Comment by tlawrie** [comment]
Sounds good. Lets go with option 3.

Linking from Docs i think we can add to that page as a link. With a nice heading about if you want to protect it etc etc.

But we can also add it as a tile to the main docs page which is where we should link off to some good blogs that are written by the time.

**Pull request merged**
